import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "../components/ReactQueryClientProvider";
import NavigationHeader from "../components/NavigationHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Movie Database",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
    <html lang="en">
      <body className={inter.className}>
        <NavigationHeader />
        <main>{children}</main>
        </body>
    </html>
    </ReactQueryClientProvider>
  );
}
